# Generated by Django 2.2.3 on 2019-07-24 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='user',
            new_name='created_by',
        ),
    ]
