# Generated by Django 2.2.3 on 2019-07-31 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0004_auto_20190731_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='issuetype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='issue_type', to='issue.IssueType'),
        ),
    ]
